### ISSUE TITLE
vimrc is not installed

### ISSUE THREAD

**Issue by hupfdule** [vim-volt/volt#273] opened 2019-04-01 08:42 UTC
```sh
$ # vimrc exists in $VOLTPATH, but not in the system
$ ls -l ~/volt/rc/default/vimrc
-rw-r--r-- 1 myuser myuser 9791 Mär 26 18:49 /home/myuser/volt/rc/default/vimrc
$ ls -l ~/.vimrc
ls: cannot access '/home/myuser/.vimrc': No such file or directory
$ ls -l ~/.vim/vimrc
ls: cannot access '/home/myuser/.vim/vimrc': No such file or directory
# calling volt to do a full build
$ volt build -full
[INFO] Full building /home/myuser/.vim/pack/volt/opt directory ...
[INFO] Installing vimrc and gvimrc ...
# checking for existance of vimrc (which should have been copied)
$ ls -l ~/.vimrc
ls: cannot access '/home/myuser/.vimrc': No such file or directory
$ ls -l ~/.vim/vimrc
ls: cannot access '/home/myuser/.vim/vimrc': No such file or directory
```

There is no error message and still nothing is copied.

**Comment by mrymtsk** [comment] 2019-04-01 23:04
Can you update #272 first? 🙏 Simply closing the issue is okay if your question is answered.

The filename should be`vimrc.vim` or `gvimrc.vim`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hupfdule** [comment] 2019-04-09 08:54
The problem was, that those file was named `vimrc` instead of `vimrc.vim` in my `$VOLTPATH`. It is documented in the README, but I think it should be pointed out explicitly, since it can be easily overlooked (as I did).

**Comment by tyru** [comment] 2019-05-26 06:13
fixed in #292

**Closed** 2019-05-26 08:02 UTC
Labels: documentation, fixed-in-devel, release/v0.3.7
